* a day of ordinary life.
***  <2013-05-15 수> // Shiny, not hot.

 A new day as always.  Expect a fine day. I am not good at English. So bad for me, but why so serious about it.

Using a emacs is not easy 4 me. I have few knowledge of programming or editor nor developing environment. There are manuals and books about emacs, I have no idea what shoud i do after all the black and white on screen and papers.


... but I am writing this log with emacs. why?

I just simply don't know. But when I saw the name, emacs in the book,[[http://pragprog.com/book/tpp/the-pragmatic-programmer][pragmatic programmer]], my heart keep calling emacs. 

I just can't help 


* organize thought
***  <2013-05-16 목> // fine day.

 need to organize things. I made a doc named 'library.org' for this purpose.

It consist of four wings and one basement.

North wing for the cold winter, reason and humane power.
East wing for the warm spring, heart and feelings.
West wing for the sollowful fall, memories and records.
South wing for the blazing summer, dream and creations.

The basement is much more simple. It is just foundation.

starting now.



* business model checking 
 - marketing point
 - trading mechanism

